name: Publish processor to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode > ~/.gradle/secring.gpg
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish to Central
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_signing.keyId: ""
          ORG_GRADLE_PROJECT_signing.password: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signing.secretKeyRingFile: ~/.gradle/secring.gpg
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.CENTRAL_PASSWORD }}
